services:
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"  # External port for Kafka
      - "9093:9093"  # Internal port for container-to-container communication
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/var/lib/kafka/data  # Persistent storage for Kafka logs

#  postgres:
#    image: postgres:15
#    container_name: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - microservices-network
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  order-service:
    build: ./order-service
    ports:
      - "8081:8080"

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8080"

  payment-service:
    build: ./payment-service
    ports:
      - "8083:8080"

  notification-service:
    build: ./notification-service
    ports:
      - "8084:8080"

volumes:
  kafka-data:
  zookeeper-data:
  postgres_data:
